name: Semgrep

on:
  push:
    branches:
      - main
      - master
      - develop
      - ci/semgrep
  pull_request:
    branches:
      - main
      - master
      - develop
  workflow_dispatch:

permissions:
  contents: read

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semgrep CE
        run: semgrep scan --config auto
